# Generated by Django 6.0.2 on 2026-02-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Development', 'Development'), ('Design', 'Design'), ('Data', 'Data'), ('Emerging Tech', 'Emerging Tech')], default='Development', max_length=50)),
                ('thumbnail', models.ImageField(help_text='Image for the listing card', upload_to='course_thumbnails/')),
                ('coursename', models.CharField(help_text='Short course name for listing card', max_length=200)),
                ('level', models.CharField(help_text='e.g., Beginner to Advanced', max_length=100)),
                ('detailtitle', models.CharField(help_text='Main title on the detail page', max_length=255)),
                ('subtitle_1', models.CharField(blank=True, max_length=255)),
                ('subtitle_2', models.CharField(blank=True, max_length=255)),
                ('subtitle_3', models.CharField(blank=True, max_length=255)),
                ('course_fee', models.CharField(help_text='e.g., ₹ 30,000', max_length=50)),
                ('duration', models.CharField(help_text='e.g., 6 Months', max_length=50)),
                ('certification', models.CharField(default='Yes', max_length=50)),
                ('mode', models.CharField(help_text='e.g., Online & Offline', max_length=100)),
                ('brochure', models.FileField(blank=True, help_text='Upload PDF brochure', null=True, upload_to='brochures/')),
                ('short_video', models.FileField(blank=True, help_text='Short overview video', null=True, upload_to='course_videos/')),
                ('course_overview', models.TextField()),
                ('tools_covered', models.CharField(help_text='Comma-separated tools (e.g., Python, Django, React, MySQL, APIs)', max_length=500)),
                ('learn', models.TextField(help_text='What you will learn. Enter each bullet point on a new line.')),
            ],
        ),
    ]
