# Generated by Django 6.0.2 on 2026-03-16 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., Surandai - April's Complex", max_length=255)),
                ('address', models.TextField(help_text='Full address to display on the card')),
                ('map_link', models.URLField(help_text='Paste the Google Maps link here', max_length=1000)),
                ('latitude', models.FloatField(blank=True, help_text='Auto-fills from link. Or enter manually (e.g., 8.9743)', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Auto-fills from link. Or enter manually (e.g., 77.3948)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Display order in the filter tabs')),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('course_interest', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='learning_environment/')),
                ('alt_text', models.CharField(blank=True, help_text='Image description', max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Food App design', max_length=255)),
                ('student_name', models.CharField(help_text='e.g., divya', max_length=100)),
                ('category', models.CharField(help_text='e.g., UI/UX Designing', max_length=100)),
                ('image', models.ImageField(upload_to='student_projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('course_or_role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='student_stories/')),
                ('video_file', models.FileField(blank=True, help_text='Upload MP4 video file', null=True, upload_to='student_videos/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Student Stories',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(help_text='Image for the listing card', upload_to='course_thumbnails/')),
                ('coursename', models.CharField(help_text='Short course name for listing card', max_length=200)),
                ('level', models.CharField(help_text='e.g., Beginner to Advanced', max_length=100)),
                ('short_description', models.CharField(blank=True, help_text="Brief description for the card (e.g., 'Build complete web applications')", max_length=255)),
                ('detailtitle', models.CharField(help_text='Main title on the detail page', max_length=255)),
                ('subtitle_1', models.CharField(blank=True, max_length=255)),
                ('subtitle_2', models.CharField(blank=True, max_length=255)),
                ('subtitle_3', models.CharField(blank=True, max_length=255)),
                ('course_fee', models.CharField(help_text='e.g., ₹ 30,000', max_length=50)),
                ('duration', models.CharField(help_text='e.g., 6 Months', max_length=50)),
                ('certification', models.CharField(default='Yes', max_length=50)),
                ('mode', models.CharField(help_text='e.g., Online & Offline', max_length=100)),
                ('brochure', models.FileField(blank=True, help_text='Upload PDF brochure', null=True, upload_to='brochures/')),
                ('short_video', models.FileField(blank=True, help_text='Short overview video', null=True, upload_to='course_videos/')),
                ('course_overview', models.TextField()),
                ('tools_covered', models.CharField(help_text='Comma-separated tools (e.g., Python, Django, React, MySQL, APIs)', max_length=500)),
                ('learn', models.TextField(help_text='What you will learn. Enter each bullet point on a new line.')),
                ('is_featured', models.BooleanField(default=False, help_text='Check this to show the course on the homepage')),
                ('job_offer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Does this course come with a job offer?', max_length=3)),
                ('benefits', models.TextField(blank=True, help_text='Course benefits. Enter each benefit on a new line.')),
                ('is_enrollable_online', models.BooleanField(default=True, help_text='If checked, the Enroll Now button will be shown on the course pages.')),
                ('category', models.ForeignKey(blank=True, help_text='Select a category (manage categories in Course Categories section)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='VTS.coursecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('mode', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VTS.course')),
            ],
        ),
    ]
