# Generated by Django 6.0.2 on 2026-03-17 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0002_enrollment_bank_rrn_enrollment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='map_link',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='VTS.coursecategory'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_fee',
            field=models.DecimalField(decimal_places=2, help_text='Course fee in rupees (e.g. 10000.00) — do NOT include ₹ symbol', max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursename',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='detailtitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_enrollable_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='job_offer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='learn',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='mode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to='course_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tools_covered',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='environmentimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentstory',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='student_videos/'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_featured'], name='course_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='course_category_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_enrollable_online'], name='course_enroll_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['-created_at'], name='enquiry_date_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['payment_status'], name='enroll_status_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['email'], name='enroll_email_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['created_at'], name='enroll_date_idx'),
        ),
    ]
