# Generated by Django 6.0.2 on 2026-02-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0003_branch_enquiry_environmentimage_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Auto-fills from link. Or enter manually (e.g., 8.9743)', null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Auto-fills from link. Or enter manually (e.g., 77.3948)', null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='map_link',
            field=models.URLField(help_text='Paste the Google Maps link here', max_length=1000),
        ),
    ]
