# Generated by Django 6.0.2 on 2026-02-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0004_alter_branch_latitude_alter_branch_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check this to show the course on the homepage'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, help_text="Brief description for the card (e.g., 'Build complete web applications')", max_length=255),
        ),
    ]
