# Generated by Django 6.0.2 on 2026-02-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0005_course_is_featured_course_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Food App design', max_length=255)),
                ('student_name', models.CharField(help_text='e.g., divya', max_length=100)),
                ('category', models.CharField(help_text='e.g., UI/UX Designing', max_length=100)),
                ('image', models.ImageField(upload_to='student_projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
