# Generated by Django 6.0.2 on 2026-02-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0006_studentproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('course_or_role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='student_stories/')),
                ('video_file', models.FileField(blank=True, help_text='Upload MP4 video file', null=True, upload_to='student_videos/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Student Stories',
                'ordering': ['order', '-id'],
            },
        ),
    ]
