# Generated by Django 6.0.2 on 2026-04-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0030_course_benefit_title_course_learn_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmentimage',
            options={'ordering': ['order'], 'verbose_name': 'Contact Environment Image & video', 'verbose_name_plural': 'Contact Environment Image & video'},
        ),
        migrations.AddField(
            model_name='environmentimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='environmentimage',
            name='video',
            field=models.FileField(blank=True, help_text='Upload .mp4 or .webm files here', null=True, upload_to='learning_environment/videos/'),
        ),
        migrations.AlterField(
            model_name='environmentimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Description for image, or title for video', max_length=255),
        ),
        migrations.AlterField(
            model_name='environmentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='learning_environment/images/'),
        ),
    ]
